const cities = [
    "Accra",
    "Addis Ababa",
    "Adelaide",
    "Agartala",
    "Ahmedabad",
    "Agra",
    "Aizawl",
    "Almaty",
    "Amman",
    "Amritsar",
    "Anand",
    "Anantapur",
    "Anantnag",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Asmara",
    "Astana",
    "Asunción",
    "Athens",
    "Atlanta",
    "Auckland",
    "Austin",
    "Baghdad",
    "Baku",
    "Baltimore",
    "Bandung",
    "Bangalore",
    "Bangkok",
    "Barcelona",
    "Barnaul",
    "Barranquilla",
    "Bartın",
    "Beijing",
    "Beirut",
    "Belém",
    "Belfast",
    "Belgrade",
    "Belgorod",
    "Bengaluru",
    "Berlin",
    "Bhopal",
    "Bhubaneswar",
    "Bilaspur",
    "Birmingham",
    "Bishkek",
    "Bisho",
    "Bogotá",
    "Boston",
    "Brasília",
    "Bratislava",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Cairo",
    "Cape Town",
    "Caracas",
    "Casablanca",
    "Chandigarh",
    "Chennai",
    "Chicago",
    "Chisinau",
    "Chittagong",
    "Chongqing",
    "Christchurch",
    "Cincinnati",
    "Cleveland",
    "Cologne",
    "Copenhagen",
    "Córdoba",
    "Curitiba",
    "Dallas",
    "Dar es Salaam",
    "Davao City",
    "Denver",
    "Detroit",
    "Dhaka",
    "Doha",
    "Dubai",
    "Dublin",
    "Durban",
    "Dushanbe",
    "Edinburgh",
    "Edmonton",
    "Erbil",
    "Faisalabad",
    "Fortaleza",
    "Frankfurt",
    "Freetown",
    "Fukuoka",
    "Funafuti",
    "Geneva",
    "George Town",
    "Glasgow",
    "Goa",
    "Goiânia",
    "Guadalajara",
    "Guangzhou",
    "Guatemala City",
    "Guayaquil",
    "Hamburg",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Hobart",
    "Ho Chi Minh City",
    "Hong Kong",
    "Honolulu",
    "Houston",
    "Hyderabad",
    "Ibadan",
    "Indianapolis",
    "Islamabad",
    "Istanbul",
    "Jacksonville",
    "Jaipur",
    "Jakarta",
    "Jeddah",
    "Jerusalem",
    "Johannesburg",
    "Kabul",
    "Kampala",
    "Karachi",
    "Kathmandu",
    "Khartoum",
    "Kiev",
    "Kinshasa",
    "Kolkata",
    "Kuala Lumpur",
    "Kunming",
    "Kuwait City",
    "Kyiv",
    "Lagos",
    "Lahore",
    "Las Vegas",
    "Leeds",
    "Leipzig",
    "Lima",
    "Lisbon",
    "Liverpool",
    "Ljubljana",
    "London",
    "Los Angeles",
    "Louisville",
    "Lucknow",
    "Lusaka",
    "Luxembourg City",
    "Lviv",
    "Madrid",
    "Madurai",
    "Makassar",
    "Malang",
    "Male",
    "Malé",
    "Managua",
    "Manama",
    "Manaus",
    "Manila",
    "Maputo",
    "Marseille",
    "Mecca",
    "Medan",
    "Medellín",
    "Melbourne",
    "Memphis",
    "Mendoza",
    "Mexico City",
    "Miami",
    "Milan",
    "Milwaukee",
    "Minneapolis",
    "Minsk",
    "Montevideo",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Muscat",
    "Nairobi",
    "Nanjing",
    "Naples",
    "Nanded",
    "Nagpur",
    "Nashville",
    "Navi Mumbai",
    "New Delhi",
    "New York",
    "New york",
    "Nicosia",
    "Niigata",
    "Nouakchott",
    "Novosibirsk",
    "Odesa",
    "Osaka",
    "Oslo",
    "Ottawa",
    "Panama City",
    "Paris",
    "Patna",
    "Perth",
    "Philadelphia",
    "Phoenix",
    "Phnom Penh",
    "Pittsburgh",
    "Port Moresby",
    "Port-au-Prince",
    "Porto Alegre",
    "Prague",
    "Pretoria",
    "Pune",
    "Quito",
    "Rabat",
    "Raleigh",
    "Ranchi",
    "Rangoon",
    "Recife",
    "Reykjavik",
    "Richmond",
    "Rio de Janeiro",
    "RiyadhTampaSy",
    "Rome",
    "Rotterdam",
    "Salvador",
    "San Diego",
    "San Francisco",
    "San José",
    "San Juan",
    "San Salvador",
    "Santiago",
    "Santo Domingo",
    "Sao Paulo",
    "Seattle",
    "Seoul",
    "Seville",
    "Shanghai",
    "Shenzhen",
    "Singapore",
    "Sofia",
    "St. Louis",
    "Stockholm",
    "Surabaya",
    "Surat",
    "Suva",
    "Sydney",
    "Tahiti",
    "Taipei",
    "Tallinn",
    "Tampa",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tel Aviv",
    "The Hague",
    "Thessaloniki",
    "Tianjin",
    "Tijuana",
    "Tokyo",
    "Toronto",
    "Tripoli",
    "Tunis",
    "Ulaanbaatar",
    "Valencia",
    "Valletta",
    "Vancouver",
    "Varanasi",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington D.C.",
    "Wellington",
    "Wuhan",
    "Xiamen",
    "Yangon",
    "Yerevan",
    "Zagreb",
    "Zanzibar City",
    "Zhengzhou",
    "Zurich"
  ];
  
  export default cities;
  